parameters:
  liuggio_help_desk.ticket.manager.class: Liuggio\HelpDeskBundle\Entity\TicketManager
  liuggio_help_desk.category.manager.class: Liuggio\HelpDeskBundle\Entity\CategoryManager
  liuggio_help_desk.ticket.listener.class: Liuggio\HelpDeskBundle\Listener\TicketNotifier

services:
#acl manager
    liuggio_help_desk.acl.manager:
          class: Liuggio\HelpDeskBundle\Service\AclManager
          arguments: [@security.acl.provider, @security.context]
#manager
    liuggio_help_desk.ticket.manager:
        class: %liuggio_help_desk.ticket.manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %liuggio_help_desk.ticket.class%, %liuggio_help_desk.comment.class%, @security.context]

    liuggio_help_desk_category.manager:
        class: %liuggio_help_desk.category.manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %liuggio_help_desk.category.class%]

    liuggio_help_desk.ticket.manager_no_doctrine:
        class: %liuggio_help_desk.ticket.manager.class%
        arguments: [null, %liuggio_help_desk.ticket.class%, %liuggio_help_desk.comment.class%, null]

    liuggio_help_desk.ticket.listener:
        class: %liuggio_help_desk.ticket.listener.class%
        arguments: [@service_container]
        tags:
          - { name: doctrine.event_listener, event:postUpdate}
          - { name: doctrine.event_listener, event:postPersist}
#Sonata Admin
    sonata.ticket.ticketstate.admin:
           class: Liuggio\HelpDeskBundle\Admin\TicketStateAdmin
           tags:
             - { name: sonata.admin, manager_type: orm, group: HelpDesk, label: TicketState }
           arguments: [null, Liuggio\HelpDeskBundle\Entity\TicketState, LiuggioHelpDeskBundle:Admin\TicketStateAdmin]

    sonata.ticket.comment.admin:
           class: Liuggio\HelpDeskBundle\Admin\CommentAdmin
           tags:
             - { name: sonata.admin, manager_type: orm, group: HelpDesk, label: Comment }
           arguments: [null, Liuggio\HelpDeskBundle\Entity\Comment, LiuggioHelpDeskBundle:Admin\CommentAdmin]

    sonata.ticket.category.admin:
           class: Liuggio\HelpDeskBundle\Admin\CategoryAdmin
           tags:
             - { name: sonata.admin, manager_type: orm, group: HelpDesk, label: Category }
           arguments: [null, Liuggio\HelpDeskBundle\Entity\Category, LiuggioHelpDeskBundle:Admin\CategoryAdmin]

    sonata.ticket.ticket.admin:
          class: Liuggio\HelpDeskBundle\Admin\TicketAdmin
          tags:
            - { name: sonata.admin, manager_type: orm, group: HelpDesk, label: Ticket }
          arguments: [null, Liuggio\HelpDeskBundle\Entity\Ticket, LiuggioHelpDeskBundle:Admin\TicketAdmin]
          calls:
            - [ setTemplates, [{"list": LiuggioHelpDeskBundle:TicketOperator:list.html.twig,layout: SonataAdminBundle::standard_layout.html.twig, ajax: SonataAdminBundle::ajax_layout.html.twig, edit: SonataAdminBundle:CRUD:edit.html.twig, show: SonataAdminBundle:CRUD:show.html.twig}] ]




